apiVersion: apps/v1
kind: Deployment
metadata:
  name: newone
spec:
  selector:
    matchLabels:
      app: newone
  replicas: 2
  template:
    metadata:
      labels:
        app: newone
    spec:
      containers:
      - name: newone
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
